name: Build & Deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update reports index.json
        run: node scripts/update-index.js

      - name: Prepare _site and cache dirs
        run: |
          mkdir -p _site .jekyll-cache
          chmod -R 777 _site .jekyll-cache

      - name: Build site with Jekyll (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            -v ${{ github.workspace }}/.jekyll-cache:/srv/jekyll/.jekyll-cache \
            jekyll/jekyll:4 \
            jekyll build \
              --destination /srv/jekyll/_site \
              --future

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          allow_empty_commit: true
